export type RootStackParamList = {
  Onboarding: undefined;
  SignIn: undefined;
  SignUp: undefined;
  RequestChange: undefined;
  SetNewPassword: undefined;
  VerifyEmail: undefined;
  SendInstructions: undefined;
  Home: undefined;
  Achievements: undefined;
  Feedback: undefined;
  FeedbackSuccess: undefined;
  Notifications: undefined;
  Profile: undefined;
  Settings: undefined;
  Informations: undefined;
  ReportProblem: undefined;
  MyDevices: undefined;
  AccountEdit: undefined;
  NightMode: undefined;
  Education: undefined;
  MeasureDetail: undefined;
};
